Home page
LocalhostLtd/localhost pull request #8
Opened 2024-04-06 12:38 UTC by dis-may

## Context

We need a home page

## What Changed?

* Added custom localhost theme with colours and fontFamily (`tailwind.config.ts` file)
* Changed components to include these themed values (touched header, footer, cards) instead of being hardcoded certain colours
* Added background (the green colour is not a div overlay because it goes over text, so its just part of the background image)
* Made a new `Heading` component which looks like a navbar but has no buttons and central text
* put the home page together as closely as I could to the Figma 

## How To Review

See if the website looks right, if its responsive, buggy, etc. Also if i made any questionable coding choices

## Testing

It should run, none of the links go anywhere but it runs and is somewhat responsive to smaller sizes.

## Notes

2024-04-07 11:18 UTC, codecreator127 requested changes
I think you have some duplicate code, but I took a look at it and it looks pretty good apart from that

2024-04-07 11:18 UTC, codecreator127 commented on src/app/home/page.tsx
what's the mainText and subText for?

2024-04-07 11:18 UTC, codecreator127 commented on src/app/layout.tsx
is there supposed to be the footer component in both layout.tsx and the page.tsx?

2024-04-07 11:21 UTC, dis-may commented on src/app/home/page.tsx
oops left it in accidentally from trying something, ill remove it

2024-04-07 11:23 UTC, dis-may commented on src/app/layout.tsx
it was removed from the `layout.tsx` page, and i put it in `page.tsx` instead

2024-04-08 04:24 UTC, codecreator127 approved these changes
looks good. go ahead and merge

2024-04-08 07:32 UTC, merged